#!/usr/bin/env python
import os

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])

# Gather source files based on platform
if env["platform"] == "ios":
    env.Append(FRAMEWORKS=["UIKit"])
    # On iOS, use .mm (Objective-C++) for haptics, skip .cpp stub
    sources = [env.Object(
        target="src/register_types.ios.o",
        source="src/register_types.cpp",
    )]
    mm_files = Glob("src/*.mm")
    for mm in mm_files:
        obj = env.Object(
            target=str(mm).replace(".mm", ".ios.o"),
            source=mm,
            CXX=env["CXX"],
            CXXFLAGS=env["CCFLAGS"] + env["CXXFLAGS"] + ["-x", "objective-c++"],
        )
        sources.append(obj)
else:
    # On non-iOS, use .cpp stub (no-op), skip .mm
    sources = Glob("src/*.cpp")

# Build library
if env["platform"] == "ios":
    library = env.StaticLibrary(
        "bin/libdaxtle_haptics.{}.{}.{}".format(
            env["platform"], env["target"], env["arch"]
        ),
        source=sources,
    )
elif env["platform"] == "macos":
    library = env.SharedLibrary(
        "bin/libdaxtle_haptics.{}.{}.framework/libdaxtle_haptics.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "bin/libdaxtle_haptics{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
